"""empty message

Revision ID: 06d371d58f0a
Revises: 0906660c7732
Create Date: 2024-08-01 23:14:32.988472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d371d58f0a'
down_revision = '0906660c7732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
