"""empty message

Revision ID: 0906660c7732
Revises: a6c94ab0237d
Create Date: 2024-08-01 23:07:22.550895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0906660c7732'
down_revision = 'a6c94ab0237d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELED', name='orderstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
