"""empty message

Revision ID: 0f4e9a3d22a1
Revises: 7d8bc650a3d4
Create Date: 2024-08-02 11:44:35.031394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4e9a3d22a1'
down_revision = '7d8bc650a3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'checkout', 'carts', ['customer_id'], ['customer_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checkout', type_='foreignkey')
    op.drop_column('checkout', 'customer_id')
    # ### end Alembic commands ###
