"""empty message

Revision ID: 39765d79f269
Revises: 
Create Date: 2024-07-30 12:23:01.749500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39765d79f269'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
