"""empty message

Revision ID: 5053be8a7c13
Revises: f121f167846d
Create Date: 2024-08-01 22:45:28.884818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5053be8a7c13'
down_revision = 'f121f167846d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
