"""empty message

Revision ID: 744a633d7d03
Revises: 39765d79f269
Create Date: 2024-08-01 11:30:44.907452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744a633d7d03'
down_revision = '39765d79f269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['name'])
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'])
    op.add_column('payment_history', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('payment_history', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('payment_history', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_history', 'is_active')
    op.drop_column('payment_history', 'updated_at')
    op.drop_column('payment_history', 'created_at')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
