"""empty message

Revision ID: 7d8bc650a3d4
Revises: 06d371d58f0a
Create Date: 2024-08-02 11:26:03.405325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8bc650a3d4'
down_revision = '06d371d58f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('order_history', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('order_history', sa.Column('price', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'order_history', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_history', type_='foreignkey')
    op.drop_column('order_history', 'price')
    op.drop_column('order_history', 'quantity')
    op.drop_column('order_history', 'product_id')
    # ### end Alembic commands ###
