"""empty message

Revision ID: 8f8a732122d5
Revises: 744a633d7d03
Create Date: 2024-08-01 13:12:07.648615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8a732122d5'
down_revision = '744a633d7d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
