"""empty message

Revision ID: a6c94ab0237d
Revises: 5053be8a7c13
Create Date: 2024-08-01 23:01:30.052864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c94ab0237d'
down_revision = '5053be8a7c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
